In [1]:
udfExampleDF = spark.range(6).toDF("num")
display(udfExampleDF)

num
0
1
2
3
4
5

In [2]:
from pyspark.sql.functions import udf

def power3(value):
  return value * value * value

power3udf = udf(power3)

In [3]:
from pyspark.sql.functions import col

display(udfExampleDF.select(power3udf(col("num"))))

power3(num)
0
1
8
27
64
125

In [4]:
from pyspark.sql.types import IntegerType, DoubleType

spark.udf.register("power3py", power3, DoubleType())

In [5]:
display(udfExampleDF.selectExpr("power3py(num)"))

power3py(num)
null
null
null
null
null
null

- null값을 반환하는 이유는 range 메서드가 Integer 데이터 타입의 데이터를 만들기 때문임. 파이썬에서 Integer 데이터 타입을 사용해서 연산을 했다면 Float 데이터 타입(스파크의 Double 데이터 타입과 동일)으로 변환할 수 없으므로 Null값을 반환. 
- 이 문제를 해결하기 위해선 파이썬 함수가 Integer 데이터 타입 대신 Float데이터 타입을 반환하도록 수정해야 함